### PR TITLE
Fixed compile error in package.json, added contributor, coupon support, and item multi-option support

### PR DESCRIPTION
**Pull request by julianh2o**
Sorry about the last one, I was showing up as unknown user and had to refork my repository.

As in the title and commit logs:
- Removed stray comma from package.json that was causing an NPM error
- added contributor to package.json
- added support for multiple options in Item.js
- added support for adding coupons to an order int Coupon.js (and Order.js)

### CODE REVIEW

**Comment by RIAEvangelist** [comment]
this looks like a nice add. Is it stil a legit pull request?

**Comment by julianh2o** [comment]
Should be, I haven't revised it lately.. but as long as it doesn't throw
any merge errors, it should be fine.

**Comment by RIAEvangelist** [comment]
It looks like some of the work has already been done in the master repo pizzapi branch. I may already have merged some into master but coupons are not in any of the branches.

When this gets merged in we'll need a way to religate the available coupons as well.

Currently I am refactoring how getMenu works to incorporate the sweet changes that have been made to the rest of the code. Since Coupons are returned in the menu for a store, with your additional class it only seems logical to include them this time.

Have you tested any of these through the full purchase flow?

**Comment by julianh2o** [comment]
I actually haven't yet gotten a full purchase flow to run successfully (with or without the changes). I'm sorta in the middle of the final step of debugging it by comparing the JSON request with one generated by the browser in a successful order.

**Comment by julianh2o** [comment]
By "sorta", I mean it's a sorta long process.. limited by the interval of time between pizza orders and the time it takes for hunger and frustration to win out over tinkering with the API. :)

**Comment by julianh2o** [comment]
I'm going to see if I can bring my fork up to date with yours and maybe re-create this pull request.

**Comment by julianh2o** [comment]
Merging this into RIAEvangelist's master instead.

**Pull request closed without merging**
